name: smart_ui_kit
description: "Smart design system package."
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  buttons_tabbar: ^1.3.8
  carousel_slider: ^4.2.1
  dropdown_button2: ^2.3.9
  extended_image: ^8.1.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  flutter_switch: ^0.3.2
  gap: ^3.0.1
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  nil: ^1.1.1
  pull_to_refresh: ^2.0.0
  skeletonizer: ^1.0.1
  smooth_page_indicator: ^1.1.0
  tap_debouncer: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/svg/logo/
    - assets/lottie/

flutter_gen:
  output: lib/src/core/generated/
  integrations:
    flutter_svg: true
    lottie: true
