targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          include:
            - lib/src/router/wrapper/**.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          include:
            - lib/src/router/**.dart
      json_serializable:
        generate_for:
          include:
            - lib/src/data/models/**.dart
        options:
          field_rename: snake
      freezed:freezed:
        generate_for:
          include:
            - lib/src/presentation/blocs/**/**.dart
            - lib/src/presentation/cubits/**/**.dart
            - lib/src/data/models/**.dart
      injectable_generator|injectable_config_builder:
        generate_for:
          include:
            - lib/src/di/**.dart
            - lib/src/data/datasources/**.dart
            - lib/src/data/repositories/**.dart
            - lib/src/domain/usecases/**.dart
            - lib/src/sorages/**.dart
            - lib/src/utils/**.dart
