name: core
description: Core module package for Smart."
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  config:
    path: ../../shared/config
  connectivity_plus: ^5.0.2
  dependencies:
    path: ../../shared/dependencies
  device_info_plus: ^8.2.2
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dio_smart_retry: ^6.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.1.0
  home:
    path: ../../features/home
  i10n:
    path: ../../shared/i10n
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter: