targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: assets/locales/
          input_file_pattern: .i18n.json
          output_directory: lib/src/translations
          output_file_name: translations.g.dart
          output_format: single_file
          locale_handling: true
          flutter_integration: true
          namespaces: true
          translate_var: translation
          enum_name: AppWidgetbookLocale
          class_name: WidgetbookTranslations
          translation_class_visibility: private
          key_case: camel
          key_map_case: camel
          param_case: pascal
          string_interpolation: dart
          flat_map: false
          translation_overrides: false
          timestamp: true
          statistics: true
