name: smart_widgetbook
description: "An example app to showcasing Smart Design System."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_syntax_view: ^4.0.0
  lottie: ^3.1.0
  provider: ^6.1.1
  slang_flutter: ^3.29.0
  smart_ui_kit:
    path: ../../packages/smart_ui_kit
  widgetbook: ^3.4.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.7
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  slang_build_runner: ^3.29.0
  very_good_analysis: ^5.1.0
  widgetbook_generator: ^3.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true
